from rdkit import Chem
functional_group_patterns = {
    'alcohol': Chem.MolFromSmarts('[#6][OH1]'),
    'phenol': Chem.MolFromSmarts('[c][OH1]'),
    'primary_amine': Chem.MolFromSmarts('[#6][NH2]'),
    'secondary_amine': Chem.MolFromSmarts('[#6][NH1][#6]'),
    'tertiary_amine': Chem.MolFromSmarts('[#6][N]([#6])[#6]'),
    'amine': Chem.MolFromSmarts('[#7]'),
    'primary_amide': Chem.MolFromSmarts('[#6][C](=[O])[NH2]'),
    'secondary_amide': Chem.MolFromSmarts('[#6][C](=[O])[NH1][#6]'),
    'tertiary_amide': Chem.MolFromSmarts('[#6][C](=[O])[N]([#6])[#6]'),
    'amide': Chem.MolFromSmarts('[#6][C](=[O])[N]'),
    'aldehyde': Chem.MolFromSmarts('[#6][C](=[O])[H]'),
    'ketone': Chem.MolFromSmarts('[#6][C](=[O])[#6]'),
    'carbonyl': Chem.MolFromSmarts('[#6]=[O]'),
    'carboxylic_acid': Chem.MolFromSmarts('[#6](=[O])[OH]'),
    'ester': Chem.MolFromSmarts('[#6][O][C](=[O])'),
    'ether': Chem.MolFromSmarts('[#6][O][#6]'),
    'thiol': Chem.MolFromSmarts('[#6][SH1]'),
    'thioether': Chem.MolFromSmarts('[#6][S][#6]'),
    'disulfide': Chem.MolFromSmarts('[#6][S][S][#6]'),
    'aryl_halide': Chem.MolFromSmarts('[c][Cl,Br,I,F]'),
    'alkyl_halide': Chem.MolFromSmarts('[#6][Cl,Br,I,F]'),
    'boronic_acid': Chem.MolFromSmarts('[B]([H])(O)(O)'),
    'boronate_ester': Chem.MolFromSmarts('[B]([O][#6])([O][#6])'),
    'alkene': Chem.MolFromSmarts('[#6]=[#6]'),
    'alkyne': Chem.MolFromSmarts('[#6]#[#6]'),
    'aromatic': Chem.MolFromSmarts('c'),
    'benzene_ring': Chem.MolFromSmarts('c1ccccc1'),
    'nitro': Chem.MolFromSmarts('[N+](=O)[O-]'),
    'nitrile': Chem.MolFromSmarts('[#6]#[N]'),
    'isocyanate': Chem.MolFromSmarts('[N]=[C]=[O]'),
    'thiocarbonyl': Chem.MolFromSmarts('[#6]=[S]'),
    'thiourea': Chem.MolFromSmarts('[N][C](=[S])[N]'),
    'urea': Chem.MolFromSmarts('[N][C](=[O])[N]'),
    'sulfonamide': Chem.MolFromSmarts('[S](=O)(=O)[N]'),
    'phosphate': Chem.MolFromSmarts('[P](=O)([OH])([OH])[OH]'),
    'imidazole': Chem.MolFromSmarts('c1[nH]cnc1'),
    'pyridine': Chem.MolFromSmarts('c1ccncc1'),
    'furan': Chem.MolFromSmarts('c1ccoc1'),
    'pyrrole': Chem.MolFromSmarts('c1cc[nH]c1'),
    'thiophene': Chem.MolFromSmarts('c1ccsc1'),
    'indole': Chem.MolFromSmarts('c1ccc2c(c1)cc[nH]2'),
    'quinoline': Chem.MolFromSmarts('c1ccc2c(c1)cccn2'),
    'isoquinoline': Chem.MolFromSmarts('c1ccc2c(c1)cncc2'),
    'azide': Chem.MolFromSmarts('[N]=[N+]=[N-]'),
    'phosphine': Chem.MolFromSmarts('[P]([#6])([#6])[#6]'),
    'silane': Chem.MolFromSmarts('[SiH3][#6]'),
    'nitrile_oxide': Chem.MolFromSmarts('[C]#[N+][O-]'),
    'sulfoxide': Chem.MolFromSmarts('[S](=[O])[#6]'),
    'sulfone': Chem.MolFromSmarts('[S](=[O])(=[O])[#6]'),
    'enolate': Chem.MolFromSmarts('[C][C](=[O])[O-]'),
    'acetylide': Chem.MolFromSmarts('[C]#[C-]'),
    'organomagnesium': Chem.MolFromSmarts('[C][Mg][Cl,Br,I]'),
    'organozinc': Chem.MolFromSmarts('[C][Zn][Cl,Br,I]'),
    'organotin': Chem.MolFromSmarts('[C][Sn]([#6])([#6])[#6]'),
    'tosylate': Chem.MolFromSmarts('[S](=O)(=O)[O][c1ccccc1]'),
    'epoxide': Chem.MolFromSmarts('[C]1[C][O]1'),
    'imine': Chem.MolFromSmarts('[C]=[N][#6]'),
    'hydrazine': Chem.MolFromSmarts('[N][N][H]'),
    'oxime': Chem.MolFromSmarts('[C]=[N][OH]'),
    'thiazole': Chem.MolFromSmarts('c1scnc1'),
    'oxazole': Chem.MolFromSmarts('c1ocnc1'),
    'pyrazole': Chem.MolFromSmarts('c1[nH]ncc1'),
    'triazole': Chem.MolFromSmarts('c1nnnc1'),
    'pyrimidine': Chem.MolFromSmarts('c1ncncc1'),
    'isoxazole': Chem.MolFromSmarts('c1onc(c1)'),
    'indazole': Chem.MolFromSmarts('c1ccc2c(c1)[nH]nc2'),
        # Alcohols and Ethers (10)
    'primary_alcohol': Chem.MolFromSmarts('[CH3][OH1]'),
    'secondary_alcohol': Chem.MolFromSmarts('[CH2]([C])[OH1]'),
    'tertiary_alcohol': Chem.MolFromSmarts('[C]([C])([C])[OH1]'),
    'allylic_alcohol': Chem.MolFromSmarts('[C]=[C][C][OH1]'),
    'benzylic_alcohol': Chem.MolFromSmarts('[c][CH2][OH1]'),
    'vinyl_ether': Chem.MolFromSmarts('[C]=[C][O][#6]'),
    'aryl_ether': Chem.MolFromSmarts('[c][O][#6]'),
    'cyclic_ether': Chem.MolFromSmarts('[C]1[O][C][C]1'),
    'acetal': Chem.MolFromSmarts('[C]([O][#6])([O][#6])[C]'),
    'ketal': Chem.MolFromSmarts('[C]([C])([O][#6])([O][#6])[C]'),

    # Amines and Nitrogen-Containing Groups (10)
    'quaternary_ammonium': Chem.MolFromSmarts('[N+]([#6])([#6])([#6])[#6]'),
    'hydrazone': Chem.MolFromSmarts('[C]=[N][N][#6]'),
    'diazo': Chem.MolFromSmarts('[C][N]=[N]'),
    'nitroso': Chem.MolFromSmarts('[C][N]=[O]'),
    'hydroxylamine': Chem.MolFromSmarts('[C][N][OH]'),
    'amidine': Chem.MolFromSmarts('[C](=[N])[N][#6]'),
    'guanidine': Chem.MolFromSmarts('[C](=[N])[N][N][#6]'),
    'nitrosamine': Chem.MolFromSmarts('[C][N]([#6])[N]=[O]'),
    'enamine': Chem.MolFromSmarts('[C]=[C][N][#6]'),
    'aromatic_amine': Chem.MolFromSmarts('[c][NH2]'),

    # Carbonyl Derivatives (10)
    'anhydride': Chem.MolFromSmarts('[C](=[O])[O][C](=[O])'),
    'acid_chloride': Chem.MolFromSmarts('[C](=[O])[Cl]'),
    'lactone': Chem.MolFromSmarts('[C]1[C](=[O])[O][C][C]1'),
    'lactam': Chem.MolFromSmarts('[C]1[C](=[O])[N][C][C]1'),
    'imido_ester': Chem.MolFromSmarts('[C](=[N])[O][#6]'),
    'ketene': Chem.MolFromSmarts('[C]=[C]=[O]'),
    'vinyl_ketone': Chem.MolFromSmarts('[C]=[C][C](=[O])[#6]'),
    'alpha_beta_unsaturated_aldehyde': Chem.MolFromSmarts('[C]=[C][C](=[O])[H]'),
    'diketone': Chem.MolFromSmarts('[C](=[O])[C][C](=[O])'),
    'beta_ketoester': Chem.MolFromSmarts('[C](=[O])[C][C](=[O])[O][#6]'),

    # Sulfur-Containing Groups (10)
    'sulfonic_acid': Chem.MolFromSmarts('[S](=O)(=O)[OH]'),
    'sulfonate_ester': Chem.MolFromSmarts('[S](=O)(=O)[O][#6]'),
    'thiolactone': Chem.MolFromSmarts('[C]1[C](=[O])[S][C][C]1'),
    'sulfinic_acid': Chem.MolFromSmarts('[S](=O)[OH]'),
    'sulfenic_acid': Chem.MolFromSmarts('[S][OH]'),
    'thioketone': Chem.MolFromSmarts('[C]=[S][#6]'),
    'dithioether': Chem.MolFromSmarts('[C][S][C][S][#6]'),
    'sulfoximine': Chem.MolFromSmarts('[S](=[O])(=[N])[#6]'),
    'thiosulfonate': Chem.MolFromSmarts('[S](=O)(=O)[S][#6]'),
    'mercaptoacetal': Chem.MolFromSmarts('[C]([S][#6])([S][#6])[C]'),

    # Phosphorus-Containing Groups (10)
    'phosphonate': Chem.MolFromSmarts('[P](=O)([O][#6])([O][#6])'),
    'phosphinate': Chem.MolFromSmarts('[P](=O)([#6])[O][#6]'),
    'phosphonium': Chem.MolFromSmarts('[P+]([#6])([#6])([#6])[#6]'),
    'phosphine_oxide': Chem.MolFromSmarts('[P](=O)([#6])([#6])[#6]'),
    'phosphite_ester': Chem.MolFromSmarts('[P]([O][#6])([O][#6])[O][#6]'),
    'phosphorane': Chem.MolFromSmarts('[P]([#6])([#6])([#6])([#6])[#6]'),
    'ylide_phosphorus': Chem.MolFromSmarts('[P+]([#6])([#6])([#6])[C-]'),
    'phosphonic_acid': Chem.MolFromSmarts('[P](=O)([OH])([OH])[#6]'),
    'phosphorothioate': Chem.MolFromSmarts('[P](=O)([S][#6])([O][#6])'),
    'phosphoramidate': Chem.MolFromSmarts('[P](=O)([N][#6])([O][#6])'),

    # Halogen-Containing Groups (10)
    'vinyl_halide': Chem.MolFromSmarts('[C]=[C][Cl,Br,I,F]'),
    'geminal_dihalide': Chem.MolFromSmarts('[C]([Cl,Br,I,F])([Cl,Br,I,F])'),
    'vicinal_dihalide': Chem.MolFromSmarts('[C]([Cl,Br,I,F])[C]([Cl,Br,I,F])'),
    'perfluoroalkyl': Chem.MolFromSmarts('[C]([F])([F])[F]'),
    'alpha_halo_ketone': Chem.MolFromSmarts('[C](=[O])[C]([Cl,Br,I,F])'),
    'benzyl_halide': Chem.MolFromSmarts('[c][C][Cl,Br,I,F]'),
    'allyl_halide': Chem.MolFromSmarts('[C]=[C][C][Cl,Br,I,F]'),
    'trifluoromethyl': Chem.MolFromSmarts('[C]([F])([F])[F]'),
    'chloroformate': Chem.MolFromSmarts('[C](=[O])[O][Cl]'),
    'halohydrin': Chem.MolFromSmarts('[C]([OH])[C]([Cl,Br,I,F])'),

    # Organometallic and Boron-Containing Groups (10)
    'organolithium': Chem.MolFromSmarts('[C][Li]'),
    'organoborane': Chem.MolFromSmarts('[B]([#6])([#6])[#6]'),
    'boronic_ester_aryl': Chem.MolFromSmarts('[c][B]([O][#6])([O][#6])'),
    'borane': Chem.MolFromSmarts('[B][H]'),
    'organocopper': Chem.MolFromSmarts('[C][Cu]'),
    'organopalladium': Chem.MolFromSmarts('[C][Pd]'),
    'organonickel': Chem.MolFromSmarts('[C][Ni]'),
    'organosilver': Chem.MolFromSmarts('[C][Ag]'),
    'vinyl_boronic_acid': Chem.MolFromSmarts('[C]=[C][B]([OH])[OH]'),
    'alkynyl_boronic_acid': Chem.MolFromSmarts('[C]#[C][B]([OH])[OH]'),

    # Heterocycles (10)
    'oxetane': Chem.MolFromSmarts('[C]1[C][O][C]1'),
    'aziridine': Chem.MolFromSmarts('[C]1[C][N][C]1'),
    'tetrazole': Chem.MolFromSmarts('c1nnn[nH]1'),
    'thiazolidine': Chem.MolFromSmarts('[C]1[S][C][N][C]1'),
    'oxazolidine': Chem.MolFromSmarts('[C]1[O][C][N][C]1'),
    'isoxazoline': Chem.MolFromSmarts('[C]1[C][O][N][C]1'),
    'pyrazolidine': Chem.MolFromSmarts('[C]1[C][N][N][C]1'),
    'benzofuran': Chem.MolFromSmarts('c1ccc2c(c1)[c][o][c]2'),
    'benzothiophene': Chem.MolFromSmarts('c1ccc2c(c1)[c][s][c]2'),
    'purine': Chem.MolFromSmarts('c1c2c(nc(n1))ncn2'),

    # Alkene and Alkyne Derivatives (10)
    'allene': Chem.MolFromSmarts('[C]=[C]=[C]'),
    'enone': Chem.MolFromSmarts('[C]=[C][C](=[O])'),
    'enyne': Chem.MolFromSmarts('[C]=[C][C]#[C]'),
    'vinyl_amine': Chem.MolFromSmarts('[C]=[C][N][#6]'),
    'diene': Chem.MolFromSmarts('[C]=[C][C]=[C]'),
    'terminal_alkyne': Chem.MolFromSmarts('[C]#[C][H]'),
    'vinyl_ester': Chem.MolFromSmarts('[C]=[C][O][C](=[O])'),
    'vinyl_sulfide': Chem.MolFromSmarts('[C]=[C][S][#6]'),
    'enolate_ester': Chem.MolFromSmarts('[C]=[C][O][C](=[O])'),
    'cumulene': Chem.MolFromSmarts('[C]=[C]=[C]=[C]'),

    # Miscellaneous Functional Groups (10)
    'carbamate': Chem.MolFromSmarts('[C](=[O])[O][N][#6]'),
    'isothiocyanate': Chem.MolFromSmarts('[N]=[C]=[S]'),
    'cyanate': Chem.MolFromSmarts('[O][C]#[N]'),
    'thiocyanate': Chem.MolFromSmarts('[S][C]#[N]'),
    'carbonate': Chem.MolFromSmarts('[C](=[O])([O][#6])[O][#6]'),
    'orthoester': Chem.MolFromSmarts('[C]([O][#6])([O][#6])[O][#6]'),
    'semicarbazone': Chem.MolFromSmarts('[C]=[N][N][C](=[O])[N]'),
    'thiosemicarbazone': Chem.MolFromSmarts('[C]=[N][N][C](=[S])[N]'),
    'azoxy': Chem.MolFromSmarts('[N]=[N+]([O-])[#6]'),
    'sulfuryl': Chem.MolFromSmarts('[S](=O)(=O)[Cl,Br]'),
}